name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install pytest pytest-asyncio ruff pymodbus paho-mqtt
      - name: Lint
        run: ruff check .
      - name: Test
        run: pytest
